language: python
python:
  - "2.7"
cache:
  pip: true
  directories:
    - /home/travis/virtualenv/python2.7/lib/python2.7/site-packages

install: "pip install -r requirements.txt"

script: ".statdev/build.py build --img-subdomain img.oldtacomamarine.com"

