collections:
  engines:
    output: true
exclude: [vendor, Gemfile*, README.md, deploy.rb, old_engines, images/unused]
defaults:
  -
    scope:
      path: ""
      type: engines
    values:
      layout: engine
sass:
  sourcemap: development
