collections:
  engines:
    output: true
exclude: [README.md, Gemfile, Gemfile.lock, buildspec.yml, old_engines]
defaults:
  -
    scope:
      path: ""
      type: engines
    values:
      layout: engine

